# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/ugrads/j/jay123q/ecen248/lab5/lab5.cache/wt [current_project]
set_property parent.project_path /home/ugrads/j/jay123q/ecen248/lab5/lab5.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo-z7-10:part0:1.0 [current_project]
read_verilog -library xil_defaultlib {
  /home/ugrads/j/jay123q/ecen248/two_one_mux.v
  /home/ugrads/j/jay123q/ecen248/four_bit_mix.v
}
synth_design -top four_bit_mux -part xc7z010clg400-1
write_checkpoint -noxdef four_bit_mux.dcp
catch { report_utilization -file four_bit_mux_utilization_synth.rpt -pb four_bit_mux_utilization_synth.pb }
